export const APP_CONSTANTS = {
  NAME: 'Web Note',
  VERSION: '0.1.0',
  API_PREFIX: '/api/v1',
  WS_PATH: '/events',

  DATA_ROOT_NAME: 'data',
  APP_DATA_ROOT_NAME: 'app-data',

  LIBRARY_CONFIG_DIR: '.webnote',
  LIBRARY_CONFIG_FILE: 'config.json',
  LIBRARY_INDEX_DIR: 'index',
  LIBRARY_CACHE_DIR: 'cache',
  LIBRARY_TRASH_DIR: 'trash',

  DEFAULT_LIBRARY_CONFIG: {
    name: '',
    path: '',
    ownerId: '',
    git: {
      enabled: false,
      remoteUrl: '',
      branch: 'main',
      authType: 'none',
      autoBackup: true,
      autoBackupSchedule: '0 * * * *',
    },
    aiIndex: {
      enabled: true,
      providerId: '',
      embedModel: '',
      chunkSize: 512,
      chunkOverlap: 50,
      excludePatterns: ['.obsidian/**', '.git/**', '.webnote/**'],
    },
    attachments: {
      defaultDir: 'attachments',
      allowedTypes: ['image/*', 'application/pdf', 'application/zip', 'audio/*', 'video/*'],
    },
    visibility: {
      showHiddenFiles: false,
      showObsidianDir: false,
      showGitDir: false,
    },
    readOnly: false,
  },

  MARKDOWN_EXTENSIONS: ['.md', '.markdown'],

  MAX_FILE_SIZE: 50 * 1024 * 1024,

  SUPPORTED_IMAGE_TYPES: [
    'image/png',
    'image/jpeg',
    'image/webp',
    'image/gif',
    'image/svg+xml',
    'image/avif',
  ],
  SUPPORTED_ATTACHMENT_TYPES: [
    'image/*',
    'application/pdf',
    'application/zip',
    'audio/*',
    'video/*',
    'application/x-excalidraw',
  ],

  DEFAULT_TRASH_RETENTION_DAYS: 30,
  TRASH_RETENTION_OPTIONS: ['never', 30, 60, 90],

  SESSION_COOKIE_NAME: 'webnote_session',
  CSRF_HEADER_NAME: 'x-csrf-token',
  CSRF_COOKIE_NAME: 'webnote_csrf',

  DEFAULT_PROVIDER_MODELS: {
    openai: {
      chat: 'gpt-4o-mini',
      embed: 'text-embedding-3-small',
      rerank: '',
    },
    ollama: {
      chat: 'llama3.1',
      embed: 'nomic-embed-text',
      rerank: '',
    },
    'lm-studio': {
      chat: 'auto',
      embed: 'auto',
      rerank: '',
    },
  },

  PROVIDER_CAPABILITIES: {
    TOOL_CALLING: 'tool_calling',
    STREAMING: 'streaming',
    EMBEDDING: 'embedding',
    RERANK: 'rerank',
    REASONING: 'reasoning',
  },

  PERMISSION_LEVELS: {
    ALLOW: 'allow',
    ASK: 'ask',
    DENY: 'deny',
  },

  PERMISSION_SCOPES: {
    GLOBAL: 'global',
    LIBRARY: 'library',
    SESSION: 'session',
  },

  AGENT_TOOLS: [
    'read_file',
    'list_directory',
    'search_files',
    'get_file_metadata',
    'create_file',
    'edit_file',
    'rename_file',
    'move_file',
    'delete_file',
    'inspect_library',
    'inspect_current_note',
    'inspect_selection',
    'git_status',
    'git_commit',
    'git_push',
    'git_pull',
  ],

  AGENT_TASK_STATUSES: [
    'pending',
    'running',
    'waiting',
    'paused',
    'completed',
    'failed',
    'cancelled',
    'interrupted',
  ],

  AUDIT_ACTIONS: {
    AUTH_LOGIN: 'auth.login',
    AUTH_LOGOUT: 'auth.logout',
    AUTH_FAILED: 'auth.failed',
    AUTH_PASSWORD_CHANGE: 'auth.password_change',
    USER_CREATE: 'user.create',
    USER_UPDATE: 'user.update',
    USER_DELETE: 'user.delete',
    USER_UNLOCK: 'user.unlock',
    SESSION_CREATE: 'session.create',
    SESSION_REVOKE: 'session.revoke',
    SESSION_REVOKE_ALL: 'session.revoke_all',
    LIBRARY_CREATE: 'library.create',
    LIBRARY_UPDATE: 'library.update',
    LIBRARY_DELETE: 'library.delete',
    LIBRARY_SHARE: 'library.share',
    LIBRARY_UNSHARE: 'library.unshare',
    LIBRARY_TRANSFER: 'library.transfer',
    FILE_CREATE: 'file.create',
    FILE_UPDATE: 'file.update',
    FILE_DELETE: 'file.delete',
    FILE_MOVE: 'file.move',
    FILE_RENAME: 'file.rename',
    FILE_RESTORE: 'file.restore',
    FILE_PERMANENT_DELETE: 'file.permanent_delete',
    TRASH_CLEANUP: 'trash.cleanup',
    GIT_INIT: 'git.init',
    GIT_COMMIT: 'git.commit',
    GIT_PUSH: 'git.push',
    GIT_PULL: 'git.pull',
    GIT_RESTORE: 'git.restore',
    AI_PROVIDER_CREATE: 'ai.provider.create',
    AI_PROVIDER_UPDATE: 'ai.provider.update',
    AI_PROVIDER_DELETE: 'ai.provider.delete',
    AI_CHAT_MESSAGE: 'ai.chat.message',
    AGENT_TASK_START: 'agent.task.start',
    AGENT_TASK_COMPLETE: 'agent.task.complete',
    AGENT_TASK_CANCEL: 'agent.task.cancel',
    AGENT_TOOL_CALL: 'agent.tool.call',
    AGENT_ROLLBACK: 'agent.rollback',
    MCP_TOKEN_CREATE: 'mcp.token.create',
    MCP_TOKEN_REVOKE: 'mcp.token.revoke',
    MCP_REQUEST: 'mcp.request',
    SETTINGS_UPDATE: 'settings.update',
    BACKUP_CREATE: 'backup.create',
    BACKUP_RESTORE: 'backup.restore',
    MIGRATION_RUN: 'migration.run',
  },

  HTTP_STATUS: {
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    TOO_MANY_REQUESTS: 429,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
  },
} as const;

export type AppConstants = typeof APP_CONSTANTS;
